config/routes.rb
Rails.application.routes.draw do
  root 'platform#home'
  get 'select_route' => 'platform#select_route'
  get 'system_map' => 'platform#view'
  get 'route_map' => 'platform#route'
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
end

app/controllers/platform_controller.rb
class PlatformController < ApplicationController
  def home
    @this_user = current_user
  end

  def select_route
    @routes = Route.all
  end

  def view
    @routes = File.open("#{Rails.root.to_s}/public/routes.geojson").read
    @bounds = File.open("#{Rails.root.to_s}/public/o-9vrf-neworleansrta.geojson").read
  end
  
  def route
    puts "Route: #{params[:route]}"
    @route = Route.find_by(short_name: params[:route])
    @routes = [@route]
    @trips = Trip.where(route_id: params[:route], service_id: "2886")
    @stops = nil
    @directions = @trips.pluck(:trip_headsign).uniq
    @times = get_weekday_route_times(params[:route]
  end

  # private
  def get_weekday_route_times(route)
    trips = Trip.where(service_id: "2886", route_id: route)
    trip_list = []
    trips.each do |this_trip|
      this_headsign = this_trip.trip_headsign
      this_trip.times.each do |time|
        trip_list.push([this_headsign, time[0], time[1]])
      end
    end
    return trip_list
  end
  # END private
end

app/helpers/platform_helper.rb
module PlatformHelper
end

app/views/platform/_map.html.erb
<script type="text/javascript">
    $(document).ready(function() { ready() });
    $(document).on("turbolinks:load", function() { ready() });
    function routeInfoPopup(feature, layer) {
        layer.bindPopup(
            "<strong>" + feature.properties.name + ": " + feature.properties.tags.route_long_name + "</strong><br />\n" +
            "<a href=\"route?route=" + feature.properties.name + "\">Route info</a>"
        )
    }
    function ready() {
        busIcon = L.icon({
            iconUrl: "<%=image_path "glyphicons-32-bus.png"%>",
            iconSize: [8,7],
            className: 'stop-icon'
        });
        if (map != undefined) {
            map.remove()
        }
        var baseLayer = L.tileLayer.provider('Stamen.Toner');
        var map = L.map('mapid', {
            center: [29.961187, -90.066967],
            zoom: 11,
            layers: [baseLayer]
        });
        //map.locate({setView: true, maxZoom: 16});
        
        var bounds = L.geoJSON(<%=bounds.html_safe%>);
        
        var routes = L.geoJSON(<%=routes.html_safe%>, {
            style: function(feature) {
                return {color: "#"+feature.properties.color};
            },
            onEachFeature: routeInfoPopup
        })
        .addTo(map);

        <% if !stops.nil? %>
            var stops = L.geoJSON(<%=stops.html_safe%>, {
                pointToLayer: function(point, latlng) {
                    return L.marker(latlng, {icon: busIcon});
                }
            }).addTo(map);
        <% end %>
        var baseMap = { "Base" : baseLayer }
        L.control.layers(baseMap, routes).addTo(map);
        map.fitBounds(bounds.getBounds());
    };
</script>

app/views/platform/_old_route_map.html.erb
<script type="text/javascript">
    $(document).on("turbolinks:load", function() {
        var map = L.map('mapid', {
            center: [29.961187, -90.066967],
            zoom: 11
        });
        map.locate({setView: true, maxZoom: 16});
        
        L.tileLayer.provider('Stamen.Toner').addTo(map);

        <% route = Route.find(route) %>
        var coordPath = <%= j route.get_shapes.to_s %>
        var pathColor = "<%= j route.route_color %>"
        var newCoordPath = [];
        <% route.get_shapes.each do |sub_route| %>
            thisRoute = <%= sub_route %>;
            newInnerPath = []
            for (var j = 0; j < coordPath[0].length; j++) {
                var lon = coordPath[0][j][0]
                var lat = coordPath[0][j][1]
                newInnerPath.push([lat, lon]);
            }
            newCoordPath.push(newInnerPath);
        <% end %>
        var polyLine = L.polyline(newCoordPath, {color: '#'+pathColor}).addTo(map);
        polyLine.bindPopup("<div style=\"padding: 5px; background-color: #<%=j route.route_color%> \
            ; color: #<%= j route.route_text_color%> \
            \"><strong>Route: \
            <%= j "#{route.route_short_name}: #{route.route_long_name}" %> \
            </strong><br /><p> \
            <%= j link_to "Info and Schedule", route_path(route: route),  style: "color: ##{route.route_text_color}"%> \
            </div>");
        map.fitBounds(polyLine.getBounds());

        //var marker = L.marker([29.961187, -90.066967]).addTo(map);

        /*var circle = L.circle([29.961187, -90.066967], {
            color: 'red',
            fillColor: '#f03',
            fillOpacity: 0.5,
            radius: 500
        }).addTo(map);*/

        /*var polygon = L.polygon([
            [29.95, -90],
            [29.94, -90.1],
            [29.93, -90]
        ]).addTo(map);*/

        //marker.bindPopup("<strong>Hello world!</strong><br/><p>This is New Orleans</p>")

        //var popup = L.popup();

        /*function onMapClick(e) {
            popup
                .setLatLng(e.latlng)
                .setContent("You clicked the map at " + e.latlng.toString())
                .openOn(map);
        }*/

        //map.on('click', onMapClick);
    });
</script>

app/views/platform/_route_map.html.erb
<script type="text/javascript">
    $(document).ready(function() { ready() });
    $(document).on("turbolinks:load", function() { ready() });
    function routeInfoPopup(feature, layer) {
        layer.bindPopup(
            "<strong>" + feature.properties.name + ": " + feature.properties.tags.route_long_name + "</strong><br />\n" +
            "<a href=\"route_map?route=" + feature.properties.name + "\">Route info</a>"
        )
    }
    function ready() {
        busIcon = L.icon({
            iconUrl: "<%=image_path "glyphicons-32-bus.png"%>",
            iconSize: [8,7],
            className: 'stop-icon'
        });
        if (map != undefined) {
            map.remove()
        }
        var baseLayer = L.tileLayer.provider('Stamen.Toner');
        var map = L.map('mapid', {
            center: [29.961187, -90.066967],
            zoom: 11,
            layers: [baseLayer]
        });
        //map.locate({setView: true, maxZoom: 16});
        
        <% @trips.each do |trip| %>
          L.polyline(<%=trip.points.to_s.html_safe%>, {color: '#<%=@route.color%>'}).addTo(map);
        <% end %>

        var baseMap = { "Base" : baseLayer }
        //L.control.layers(baseMap).addTo(map);
        //map.fitBounds(bounds.getBounds());
    };
</script>

app/views/platform/_system_map.html.erb
<script type="text/javascript">
    $(document).on("turbolinks:load", function() {
        var map = L.map('mapid', {
            center: [29.961187, -90.066967],
            zoom: 11
        });
        map.locate({setView: true, maxZoom: 16});
        
        L.tileLayer.provider('Stamen.Toner').addTo(map);

        <% routes = Route.all %>
        <% routes.each do |route| %>
            var coordPath = <%= j route.get_shapes.to_s %>
            var pathColor = "<%= j route.route_color %>"
            var newCoordPath = [];
            <% route.get_shapes.each do |sub_route| %>
                thisRoute = <%= sub_route %>;
                newInnerPath = []
                for (var j = 0; j < coordPath[0].length; j++) {
                    var lon = coordPath[0][j][0]
                    var lat = coordPath[0][j][1]
                    newInnerPath.push([lat, lon]);
                }
                newCoordPath.push(newInnerPath);
            <% end %>
            var polyLine = L.polyline(newCoordPath, {color: '#'+pathColor}).addTo(map);
            polyLine.bindPopup("<div style=\"padding: 5px; background-color: #<%=j route.route_color%> \
                ; color: #<%= j route.route_text_color%> \
                \"><strong>Route: \
                <%= j "#{route.route_short_name}: #{route.route_long_name}" %> \
                </strong><br /><p> \
                <%= j link_to "Info and Schedule", route_map_path(route: route),  style: "color: ##{route.route_text_color}"%> \
                </div>");
            map.fitBounds(polyLine.getBounds());
        <% end %>


        //var marker = L.marker([29.961187, -90.066967]).addTo(map);

        /*var circle = L.circle([29.961187, -90.066967], {
            color: 'red',
            fillColor: '#f03',
            fillOpacity: 0.5,
            radius: 500
        }).addTo(map);*/

        /*var polygon = L.polygon([
            [29.95, -90],
            [29.94, -90.1],
            [29.93, -90]
        ]).addTo(map);*/

        //marker.bindPopup("<strong>Hello world!</strong><br/><p>This is New Orleans</p>")

        //var popup = L.popup();

        /*function onMapClick(e) {
            popup
                .setLatLng(e.latlng)
                .setContent("You clicked the map at " + e.latlng.toString())
                .openOn(map);
        }*/

        //map.on('click', onMapClick);
    });
</script>

app/views/platform/home.html.erb
<div class="jumbotron home-jumbotron">
  <div class="home-jumbotron-inner">
    <h1>NORTA Finder</h1>
    <small>
    Cover image by Vegasjon [<a href="https://creativecommons.org/licenses/by-sa/3.0">CC BY-SA 3.0 </a>], <a href="https://commons.wikimedia.org/wiki/File:New_Orleans_streetcar_stop.jpg">from Wikimedia Commons</a>
    </small>
  </div>
</div>

<%= current_user %>

<!--<div class="col-xs-6">
  <% if !user_signed_in? %>
    <%= link_to "Create an Account", new_user_registration_path, id: "create_user", method: :get, class: "btn btn-success btn-block btn-sm" %>
    <%= link_to "Sign In with Email", new_user_session_path, id: "sign_in", method: :get, class: "btn btn-primary btn-block btn-sm" %>
    <%= link_to "Sign In with Facebook", user_facebook_omniauth_authorize_path, id: "sign_in_fb", method: :get, class: "btn btn-primary btn-block btn-sm" %>
  <% else %>
    <%= link_to "Edit User Settings", edit_user_registration_path, id: "edit_user", method: :get, class: "btn btn-danger btn-block btn-sm" %>
    <%= link_to "Sign Out", destroy_user_session_path, id: "sign_out", method: :delete, class: "btn btn-danger btn-block btn-sm" %>
  <% end %>
</div>-->

<div class="col-xs-8 col-xs-offset-2">
  <%= link_to "View Stops Near Me", "#", class: "btn btn-default btn-block" %>
  <%= link_to "View System Map", system_map_path, class: "btn btn-default btn-block" %>
  <%= link_to "Select A Route", select_route_path, class: "btn btn-default btn-block" %>
</div>

app/views/platform/old_route.html.erb
<div class="col-xs-12 col-md-6">
  <div id="mapid"></div>
</div>
<div class="col-xs-12 col-md-5">
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="schedule-box">
      <% @directions.keys.each_with_index do |key1, index| %>
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="heading-<%=index%>">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-<%=index%>" aria-expanded="true" aria-controls="collapse-<%=index%>">
              <%=key1%>
              </a>
            </h4>
          </div>
          <div id="collapse-<%=index%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<%=index%>">
            <div class="panel-body">
              <table class="table table-striped">
                <% @directions[key1].each do |hash| %>
                  <tr>
                    <td><strong><%=hash[0]%></strong></td>
                    <% hash[1].sort.each do |time| %>
                      <% split_time = time.split(':') %>
                      <% if split_time[0] == "24" %>
                        <% now_date = DateTime.now %>
                        <% this_time = DateTime.new(now_date.year, now_date.month, now_date.day + 1, split_time[0].to_i-24, split_time[1].to_i, split_time[2].to_i) %>
                        <td><%=this_time.strftime("%l:%M %p\n(%m/%d)")%></td>
                      <% else %>
                        <% this_time = Time.parse(time) %>
                        <td><%=this_time.strftime("%l:%M %p")%></td>
                      <% end %>
                    <% end %>
                  </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render "map", {routes: @routes, bounds: @bounds, stops: @display_stops} %>
<script type="text/javascript">
    $('.navbar-brand').append(" - <%="#{JSON.parse(@routes)['properties']['name']}: #{JSON.parse(@routes)['properties']['tags']['route_long_name']}"%>")
</script>

app/views/platform/route.html.erb

<div class="col-xs-12 col-md-6">
  <div id="mapid"></div>
</div>

<div class="col-xs-12 col-md-5">
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="schedule-box">
      <% @directions.each_with_index do |headsign, index| %>
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="heading-<%=index%>">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-<%=index%>" aria-expanded="true" aria-controls="collapse-<%=index%>">
              <%=headsign%>
              </a>
            </h4>
          </div>
          <div id="collapse-<%=index%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<%=index%>">
            <div class="panel-body">
              <table class="table table-striped">
                <tr>
                  <td></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render "route_map", {routes: @routes, bounds: @bounds, stops: @stops} %>
<script type="text/javascript">
    $('.navbar-brand').append(" - <%="#{@route.short_name}: #{@route.long_name}"%>")
</script>

app/views/platform/select_route.html.erb
<% @routes.each do |route| %>
  <%= link_to "#{route.short_name}: #{route.long_name}", route_map_path(route: route.short_name), class: "btn btn-lg btn-block", style: "background-color: \##{route.color}; color: \##{route.text_color};" %>
<% end %>

app/views/platform/view.html.erb
<% title_add = "All Routes" %>
<div id="mapid"></div>

<%= render "map", {routes: @routes, bounds: @bounds, stops: nil} %>